### ISSUE TITLE
Are there plans to add support for Wasmtime?

### ISSUE THREAD

**Issue by yerke** [kuasar-io/kuasar#19]
### What would you like to be added?

The readme mentions both Wasmtime and Wasmedge initially in wasm sections, but then mentions that only Wasmedge is currently supported. Are there plans to add support for Wasmtime?

### Why is this needed?

Wasmtime is a popular wasm engine with 12K starts on Github vs 6K for Wasmedge. It is backed by Bytecode Alliance, which consists of many organizations. Adding support for Wasmtime should allow for easier adoption of Kuasar.

**Comment by abel-von** [comment]
@yerke we make a first implementation of wasmtime now, please pull the newest codes and take a try.

**Comment by abel-von** [comment]
Sorry it is not merged yet, please review this PR if you got time, https://github.com/kuasar-io/kuasar/pull/47
