### ISSUE TITLE
1

### ISSUE THREAD

**Issue by gj199575** [kuasar-io/kuasar#26]
### What happened?

E0609 10:45:54.021326   14308 remote_runtime.go:326] "StartContainer from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd task: failed to start shim: symlink /run/kuasar-vmm/5fc2f80bdcb842544b8b468588c93d75766bb03326954c96dba00bae196cfca8/c74f27e812a9bec410eade712ab87a40303848001a269a01d63ccee3ce2f58c0 /run/containerd/io.containerd.runtime.v2.task/k8s.io/c74f27e812a9bec410eade712ab87a40303848001a269a01d63ccee3ce2f58c0: no such file or directory: unknown" containerID="c74f27e812a9bec410eade712ab87a40303848001a269a01d63ccee3ce2f58c0"
FATA[0041] running container: starting the container "c74f27e812a9bec410eade712ab87a40303848001a269a01d63ccee3ce2f58c0": rpc error: code = Unknown desc = failed to create containerd task: failed to start shim: symlink /run/kuasar-vmm/5fc2f80bdcb842544b8b468588c93d75766bb03326954c96dba00bae196cfca8/c74f27e812a9bec410eade712ab87a40303848001a269a01d63ccee3ce2f58c0 /run/containerd/io.containerd.runtime.v2.task/k8s.io/c74f27e812a9bec410eade712ab87a40303848001a269a01d63ccee3ce2f58c0: no such file or directory: unknown 

### What did you expect to happen?

1

### How can we reproduce it (as minimally and precisely as possible)?

1

### Anything else we need to know?

1

**Comment by renzhengeek** [comment]
crictl seems to use k8s.io ns by default.
manually mkdir /run/containerd/io.containerd.runtime.v2.task/k8s.io can solves this.

**Comment by renzhengeek** [comment]
could someone modify the subject to say the error?
