### ISSUE TITLE
Improve the example scripts

### ISSUE THREAD

**Issue by leviyanx** [kuasar-io/kuasar#30]
Crictl has added a validation that requires UID, name, and namespace to be fully specified in the definition of the pod, otherwise reports message: `getting sandbox status of pod "xxx": metadata.Name, metadata.Namespace or metadata.Uid is not in metadata "&PodSandboxMetadata{Name:xxx,Uid:,Namespace:default,Attempt:0,}" when using crictl to remove wasm pod`. The definition of `pod.json` in both example scripts is missing the specification for UID.
![image](https://github.com/kuasar-io/kuasar/assets/43806292/5a5aaf7b-94b2-4592-a19b-88e77bb90da0)

**Comment by dierbei** [comment]
> Crictl has added a validation that requires UID, name, and namespace to be fully specified in the definition of the pod, otherwise reports message: `getting sandbox status of pod "xxx": metadata.Name, metadata.Namespace or metadata.Uid is not in metadata "&PodSandboxMetadata{Name:xxx,Uid:,Namespace:default,Attempt:0,}" when using crictl to remove wasm pod`. The definition of `pod.json` in both example scripts is missing the specification for UID. ![image](https://user-images.githubusercontent.com/43806292/246354582-5a5aaf7b-94b2-4592-a19b-88e77bb90da0.png)

Thanks, I'll try to fix this.
