### ISSUE TITLE
vmm-task is built explicitly with x86_64-unknown-linux-musl in Makefile

### ISSUE THREAD

**Issue by xukobe** [kuasar-io/kuasar#7]
### What happened?

Failed to build with arm64 machine. However, I noticed that arm will be supported in 2024, but explicitly specify the x86 target in the Makefile is not a good manner

### What did you expect to happen?

Built in arm64

### How can we reproduce it (as minimally and precisely as possible)?

Build with arm machine

**Comment by Burning1020** [comment]
Yes, we are not support on aarch64 platform at present, while it is on our [Roadmap](https://kuasar.io/docs/roadmap/#2024).
Let's keep this open.

**Comment by Vanient** [comment]
already fixed by https://github.com/kuasar-io/kuasar/pull/11

**Comment by Vanient** [comment]
already fixed by https://github.com/kuasar-io/kuasar/pull/11
