### ISSUE TITLE
Should kill all processes even though bundle path has been removed

### ISSUE THREAD

**Issue by yuqitao** [kuasar-io/kuasar#76]
### What happened?

When container exits，we should kill all processes even though bundle path has been removed, otherwise maybe it will cause process leak.
```
async fn should_kill_all_on_exit(bundle_path: &str) -> bool {
    match read_spec(bundle_path).await {
        Ok(spec) => has_shared_pid_namespace(&spec),
        Err(e) => {
            error!(
                "failed to read spec when call should_kill_all_on_exit: {}",
                e
            );
            false
        }
    }
}
```

containerd shim: https://github.com/containerd/containerd/commit/a687d3a36dac0c75adcef6318a1891034b4cc284#diff-3cd530e1b2d5464c8186bf3bf63e8be48df4107e853ee107751f862c7b503658R549-R554

### What did you expect to happen?

When the bundle path has been removed concurrently，we must guarantee other processes can still been killed.

### How can we reproduce it (as minimally and precisely as possible)?

create pod and delete it continuously,  sometimes we will find process leak.

**Comment by Burning1020** [comment]
Yes. Would you like to fix it?

**Comment by yuqitao** [comment]
@Burning1020 have submitted a pr
