### ISSUE TITLE
Publish new release by Github Action

### ISSUE THREAD

**Issue by Burning1020** [kuasar-io/kuasar#81]
### What would you like to be added?

Add a new Github Action for new releases. Like this: https://github.com/kuasar-io/kuasar/releases/tag/v0.1.0

The fist tar file `kuasar-vx.y.z-linux-amd64.tar.gz` compresses this binaries:
+ `vmm-sandboxer`(for Cloud Hypervisor) and `config_clh.toml`
+ `kuasar.image` and `vmlinux.bin` for Cloud Hypervisor
+ `wasm-sandboxer`(for wasmEdge)
+ `quark-sandboxer`
+ `containerd` binary and `config.toml` of Kuasar community
+ `shim` folder with two shim binaries

The second tar file `kuasar-vx.y.z-vendor.tar.gz` compresses the source code with vendor code.

The x.y.z represents the tag or version number of this release.

### Why is this needed?

Currently, Kuasar releases are manually executed and should be improved with automatic pipeline.

**Comment by xiaods** [comment]
this feature is done?
