### ISSUE TITLE
Support for runc container

### ISSUE THREAD

**Issue by Burning1020** [kuasar-io/kuasar#83]
### What would you like to be added?

Support to run [Runc](https://github.com/opencontainers/runc) containers.

### Why is this needed?

Runc container uses Linux Namespace/Cgroup trchnology to isolate containers and it is widely used.

**Comment by xiaods** [comment]
I am k8e - kubernetes engine owner, i would like this feature coming asap. How can mentor me to implement it?

**Comment by Burning1020** [comment]
Thanks, I will context you, are you in our Slack channel?

**Comment by xiaods** [comment]
> @xiaods Thanks, I will contact you, are you in our Slack channel?

yes, i am in, Deshi Xiao(you)

**Comment by xiaods** [comment]
Could you share how to configure kuasar and runc together into a k8s cluster and make containers run properly?

**Comment by Burning1020** [comment]
> Could you share how to configure kuasar and runc together into a k8s cluster and make containers run properly?

Supporting for Runc in Kuasar is still in developing. The configuration way is same as vmm descriped in this doc: https://github.com/kuasar-io/kuasar/blob/main/docs/containerd.md#configure-containerd

If you want to use runc without Kuasar, the configuration way is adding runc runtime to cri config and install runc shim.

**Comment by xiaods** [comment]
> https://github.com/kuasar-io/kuasar/blob/main/docs/containerd.md#configure-containerd

hi @Burning1020 Can i use runc with Kuasar, does it works like a charm.

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]

**Comment by xiaods** [comment]
this is PR for runc: https://github.com/kuasar-io/kuasar/pull/94

**Comment by xiaods** [comment]
any update?

**Comment by Burning1020** [comment]
fix in #94
