### ISSUE TITLE
Some sandboxer can only run on bare metal， this should be highlighted in the doc

### ISSUE THREAD

**Issue by abel-von** [kuasar-io/kuasar#96]
### What happened?

New comers follow the doc to try to install and start kuasar container, and find that it can not started in the vm at last.

### What did you expect to happen?

We should highlight the requirement of hardware in the doc to avoid it.

### How can we reproduce it (as minimally and precisely as possible)?

yes

**Comment by xiaods** [comment]
I noticed in the Firecracker sandbox solution that it is mentioned that virtualization-enabled VM services, such as those provided by AWS, are supported. It needs to be clarified what kind of virtual machines are required for this support.
